<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5OYeTo8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5OYeTo8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5OYeTo8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5OYeTo8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5OYeTo8\App_KernelDevDebugContainer([
    'container.build_hash' => '5OYeTo8',
    'container.build_id' => '51edbf16',
    'container.build_time' => 1580986886,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5OYeTo8');
